// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ENavItem: typeof import('elektro')['ENavItem']
    ETitle: typeof import('elektro')['ETitle']
    EWindowBorder: typeof import('elektro')['EWindowBorder']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
  }
}

export { }
