// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EContent: typeof import('elektro')['EContent']
    EStack: typeof import('elektro')['EStack']
    ETitle: typeof import('elektro')['ETitle']
    EWindowBorder: typeof import('elektro')['EWindowBorder']
    Nav: typeof import('./src/components/Nav.vue')['default']
  }
}

export { }
